create table "public"."capacity_ledger" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "potion" boolean default false,
    "barrel" boolean default false,
    "quantity" integer default 0,
    "delivered" boolean default false
);


alter table "public"."capacity_ledger" enable row level security;

CREATE UNIQUE INDEX capacity_ledger_pkey ON public.capacity_ledger USING btree (id);

alter table "public"."capacity_ledger" add constraint "capacity_ledger_pkey" PRIMARY KEY using index "capacity_ledger_pkey";

grant delete on table "public"."capacity_ledger" to "anon";

grant insert on table "public"."capacity_ledger" to "anon";

grant references on table "public"."capacity_ledger" to "anon";

grant select on table "public"."capacity_ledger" to "anon";

grant trigger on table "public"."capacity_ledger" to "anon";

grant truncate on table "public"."capacity_ledger" to "anon";

grant update on table "public"."capacity_ledger" to "anon";

grant delete on table "public"."capacity_ledger" to "authenticated";

grant insert on table "public"."capacity_ledger" to "authenticated";

grant references on table "public"."capacity_ledger" to "authenticated";

grant select on table "public"."capacity_ledger" to "authenticated";

grant trigger on table "public"."capacity_ledger" to "authenticated";

grant truncate on table "public"."capacity_ledger" to "authenticated";

grant update on table "public"."capacity_ledger" to "authenticated";

grant delete on table "public"."capacity_ledger" to "service_role";

grant insert on table "public"."capacity_ledger" to "service_role";

grant references on table "public"."capacity_ledger" to "service_role";

grant select on table "public"."capacity_ledger" to "service_role";

grant trigger on table "public"."capacity_ledger" to "service_role";

grant truncate on table "public"."capacity_ledger" to "service_role";

grant update on table "public"."capacity_ledger" to "service_role";


