revoke delete on table "public"."global_inventory" from "anon";

revoke insert on table "public"."global_inventory" from "anon";

revoke references on table "public"."global_inventory" from "anon";

revoke select on table "public"."global_inventory" from "anon";

revoke trigger on table "public"."global_inventory" from "anon";

revoke truncate on table "public"."global_inventory" from "anon";

revoke update on table "public"."global_inventory" from "anon";

revoke delete on table "public"."global_inventory" from "authenticated";

revoke insert on table "public"."global_inventory" from "authenticated";

revoke references on table "public"."global_inventory" from "authenticated";

revoke select on table "public"."global_inventory" from "authenticated";

revoke trigger on table "public"."global_inventory" from "authenticated";

revoke truncate on table "public"."global_inventory" from "authenticated";

revoke update on table "public"."global_inventory" from "authenticated";

revoke delete on table "public"."global_inventory" from "service_role";

revoke insert on table "public"."global_inventory" from "service_role";

revoke references on table "public"."global_inventory" from "service_role";

revoke select on table "public"."global_inventory" from "service_role";

revoke trigger on table "public"."global_inventory" from "service_role";

revoke truncate on table "public"."global_inventory" from "service_role";

revoke update on table "public"."global_inventory" from "service_role";

revoke delete on table "public"."global_inventory_temp" from "anon";

revoke insert on table "public"."global_inventory_temp" from "anon";

revoke references on table "public"."global_inventory_temp" from "anon";

revoke select on table "public"."global_inventory_temp" from "anon";

revoke trigger on table "public"."global_inventory_temp" from "anon";

revoke truncate on table "public"."global_inventory_temp" from "anon";

revoke update on table "public"."global_inventory_temp" from "anon";

revoke delete on table "public"."global_inventory_temp" from "authenticated";

revoke insert on table "public"."global_inventory_temp" from "authenticated";

revoke references on table "public"."global_inventory_temp" from "authenticated";

revoke select on table "public"."global_inventory_temp" from "authenticated";

revoke trigger on table "public"."global_inventory_temp" from "authenticated";

revoke truncate on table "public"."global_inventory_temp" from "authenticated";

revoke update on table "public"."global_inventory_temp" from "authenticated";

revoke delete on table "public"."global_inventory_temp" from "service_role";

revoke insert on table "public"."global_inventory_temp" from "service_role";

revoke references on table "public"."global_inventory_temp" from "service_role";

revoke select on table "public"."global_inventory_temp" from "service_role";

revoke trigger on table "public"."global_inventory_temp" from "service_role";

revoke truncate on table "public"."global_inventory_temp" from "service_role";

revoke update on table "public"."global_inventory_temp" from "service_role";

alter table "public"."global_inventory" drop constraint "global_inventory_pkey";

alter table "public"."global_inventory_temp" drop constraint "global_inventory_temp_pkey";

drop index if exists "public"."global_inventory_pkey";

drop index if exists "public"."global_inventory_temp_pkey";

drop table "public"."global_inventory";

drop table "public"."global_inventory_temp";

create table "public"."wishlist" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "red" integer not null,
    "green" integer not null,
    "blue" integer not null,
    "dark" integer not null,
    "quantity" integer,
    "exclude" boolean default false
);


alter table "public"."wishlist" enable row level security;

alter table "public"."customers" add column "completed" boolean default false;

alter table "public"."inventory_ledger" add column "reason" text;

alter table "public"."potion_ledger" add column "reason" text;

alter table "public"."potions" drop column "quantity";

CREATE UNIQUE INDEX wishlist_pkey ON public.wishlist USING btree (id, red, green, blue, dark);

alter table "public"."wishlist" add constraint "wishlist_pkey" PRIMARY KEY using index "wishlist_pkey";

grant delete on table "public"."wishlist" to "anon";

grant insert on table "public"."wishlist" to "anon";

grant references on table "public"."wishlist" to "anon";

grant select on table "public"."wishlist" to "anon";

grant trigger on table "public"."wishlist" to "anon";

grant truncate on table "public"."wishlist" to "anon";

grant update on table "public"."wishlist" to "anon";

grant delete on table "public"."wishlist" to "authenticated";

grant insert on table "public"."wishlist" to "authenticated";

grant references on table "public"."wishlist" to "authenticated";

grant select on table "public"."wishlist" to "authenticated";

grant trigger on table "public"."wishlist" to "authenticated";

grant truncate on table "public"."wishlist" to "authenticated";

grant update on table "public"."wishlist" to "authenticated";

grant delete on table "public"."wishlist" to "service_role";

grant insert on table "public"."wishlist" to "service_role";

grant references on table "public"."wishlist" to "service_role";

grant select on table "public"."wishlist" to "service_role";

grant trigger on table "public"."wishlist" to "service_role";

grant truncate on table "public"."wishlist" to "service_role";

grant update on table "public"."wishlist" to "service_role";


